### ISSUE TITLE
.NETFramework,Version=v4.8 were not found error

### ISSUE THREAD

**Issue by Arctic-Viper** [Mrakovic-ORG/Privilege_Escalation#1]
getting this error and not seeing a NETFramwork for Linux thats V4.8 tried using the normal installer but nothing.

**Comment by MrakDev** [comment]
Are you trying to use it on linux?

**Comment by Arctic-Viper** [comment]
Yeah isint that where your suppose you use it?

**Comment by MrakDev** [comment]
Negative!
It's a UAC bypass, so you should use it on Windows

**Comment by Arctic-Viper** [comment]
Yea I know but I'm getting that error trying to build the application via Linux... Not that dumb XD
