### ISSUE TITLE
Bypass blocked

### ISSUE THREAD

**Issue by Arctic-Viper** [Mrakovic-ORG/Privilege_Escalation#2]
![Untitled](https://user-images.githubusercontent.com/48611080/74759319-9b9a7200-5246-11ea-8fac-a9eb8c11094c.png)
Your UAC bypass is blocked on my network...any fix?
Thanks

**Comment by 0x11DFE** [comment]
Hello, Unfortunately you need to have access to fodhelper for win 10 bypass to open your own app.
