### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [Mrakovic-ORG/Privilege_Escalation#3]

**Comment by 0x11DFE** [comment]
Hello, happy to hear you appreciate our project !
You can join our Telegram here: https://t.me/wannabe1337
Or visit our website https://wannabe1337.xyz/

See you shortly.

**Comment by graysuit** [comment]
Sir any other platform please ?
Because I don't have mobile, Telegram ask for mobile number and I work on laptop,
Any other chat ?
Facebook, Instagram, LinkedIn, twitter,discord app, messenger ?

Which don't require mobile.

**Comment by 0x11DFE** [comment]
No sadly i am only available on Telegram

**Comment by graysuit** [comment]
So please meet me here,
Its my own chat app in php,
OKAY.
http://freetalk.freeweb.pk

**Comment by 0x11DFE** [comment]
Sorry i don't feel it safe to chat on an unknown website.

**Comment by graysuit** [comment]
Seriously, no chat is secure now,
But I respect your thoughts.

OKAY leave them all,
Let's come to our point.

Do you have any knowledge about Hidden RDP, Reverse Proxy, AMSI bypass ?
Will you please give guidance about them.

**Comment by 0x11DFE** [comment]
I will not give any personal advice for such things. (pretty black hat)

**Comment by graysuit** [comment]
No I don't want advise,
I want code or link etc,

Learning these things will not be black hat,
Just doing bad will be black hat.

**Comment by 0x11DFE** [comment]
Exactly, If i start sending potential destructive code i could get involved indirectly.

**Comment by graysuit** [comment]
Okay thanks for your positive replies.
